import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "./components/ui/Modal";
import Navbar from "./components/chrome/Navbar";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "CCW Canvas",
  description: "Generated by hcapan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="m-0 p-0 w-screen min-h-screen overflow-x-hidden">
        <ModalProvider>
          <Navbar />
          {children}
          <Toaster
            position="bottom-right"
            theme="light"
            richColors
            closeButton
            toastOptions={{
              className: "text-xs",
              style: {
                fontFamily: "inherit",
              },
            }}
          />
        </ModalProvider>
      </body>
    </html>
  );
}
